#!/bin/sh
# Hardened mingw gcc wrapper

/var/tmp/dist/mingw-w64/bin/i686-w64-mingw32-g++ -Wl,--dynamicbase -Wl,--nxcompat -Wl,--enable-reloc-section -fstack-protector-all -D_FORTIFY_SOURCE=2 -fno-strict-overflow "$@"
