#!/bin/sh

basedir=$(dirname "$0")

# Check if the system has a more recent version of libstdc++.so.6; if yes, use
# that instead of the bundled version.
"$basedir/abicheck" >/dev/null 2>&1
if [ $? -ne 0 ]; then
  LD_LIBRARY_PATH="$basedir/TorBrowser/Tor/libstdc++/"
  export LD_LIBRARY_PATH
fi

exec "$basedir/firefox.real" "$@"
